name: Build Ergohaven

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:

jobs:

  build-ergohaven:
    name: Build Ergohaven keymaps
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli

    steps:
    - name: (actions) Checkout Vial repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        submodules: recursive

    - name: Build
      id: build
      run: |
        git config --global --add safe.directory $(pwd)
        qmk compile -kb ergohaven/k03 -km v1
        qmk compile -kb ergohaven/imperial44 -km v1
        qmk compile -kb ergohaven/velvet/rev1 -km v1
        qmk compile -kb ergohaven/velvet -km v2
        qmk compile -kb ergohaven/hpd -km v1
        qmk compile -kb ergohaven/k02 -km v1
        qmk compile -kb ergohaven/remnant -km v1
        qmk compile -kb ergohaven/planeta/rev1 -km v1
        qmk compile -kb ergohaven/planeta -km v2
        qmk compile -kb ergohaven/macropad -km v1
        qmk compile -kb ergohaven/classic_dactyl -km vial

    - uses: actions/upload-artifact@v4
      name: Upload
      id: upload
      with:
        path: .build/*.uf2
        name: ergohaven_fw
